apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: example-quay
  annotations:
    quay.io/repository-slug: gazarenk/backstage-operator
spec:
  owner: guest
  type: service
  lifecycle: experimental
