apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: example-quay
  annotations:
    quay.io/repository-slug: gazarenk/backstage-operator
spec:
  type: service
  lifecycle: experimental
  owner: Janus-IDP Authors
